### ISSUE TITLE
Proximity API permissions

### ISSUE THREAD

**Issue by keremgocen** [google/beacon-platform#13]
I'm confused about the permissions for registration and monitoring. I setup an unregistered namespace and instance id in order to try the sample Android app here, and picked my google account to use (register/monitor etc.) it. When the app encounters my custom UID, I see the following "Not Authorized" message;

![proximity_api](https://cloud.githubusercontent.com/assets/119362/9578118/0513f304-4ff0-11e5-876a-e05d136606c6.png)

This kind of blocks me from registering my own beacons in the first place, let alone providing other users a provisioning app to use it for monitoring and registering their beacons via my app(through Oauth). Am I missing something?

**Comment by mashbridge** [comment]
The 403 likely means you haven't configured your authorisation credentials correctly. See the README here: https://github.com/google/beacon-platform/tree/master/samples/android, and particularly the Requirements section and the steps to "Registering the app with the Google Developers Console". It's a little fiddly and if you don't get things exactly right then all your requests will be refused with a 403 not authorised error.

**Comment by keremgocen** [comment]
Thank you, I just compiled and ran the app. Did not use the developer console to bind it's key/bundle for my account.

Does this enforce a <Google Developer Console account and the key that compiles the application> pair bound, instead of a <application and user account> bound? 

What I'm trying to mean is, if I configure my authorization credentials right, may another google account provision their beacons via my app, once the app is released with appropriate settings?

**Comment by mashbridge** [comment]
We're working on some improvements on the server side to make sharing of apps and resources easier. Right now you can give your app to other people if you've given them permission in your developers console project, but anything they register will be "owned" by that project.

**Comment by keremgocen** [comment]
Understood, thanks.

**Comment by tomhoward2** [comment]
@mashbridge do you have any updates regarding your last comment?

**Comment by mashbridge** [comment]
https://developers.google.com/beacons/proximity/sharing
