### ISSUE TITLE
Instructions not clear for setting up iOS key

### ISSUE THREAD

**Issue by leolobato** [google/beacon-platform#15]
To setup the API keys, the iOS sample README mentions:

> On the left of the Developers Console, click on "APIs & auth", and then on "Credentials". Press "Create new Key" to create a Public API access key.
> Choose 'iOS Key'.

But there is no 'iOS Key' option on the panel. The user must first choose "API Key" from the dropdown menu and then a "iOS Key" button will be visible.

**Comment by marcwan** [comment]
Oh man, they changed it again? Thanks for pointing it out, I'll update the docs #facepalm

**Comment by marcwan** [comment]
Fixed!
