### ISSUE TITLE
Can I run this example in older android version as SDK 19 ?

### ISSUE THREAD

**Issue by zentechthaingo** [google/beacon-platform#18]
In this example use android 22 libary. I can use this libary for other version android.

**Comment by mashbridge** [comment]
No, sorry. The code relies on the Bluetooth LE Android Platform APIs that were available in API 21, so that's as low as you can go. But it shouldn't be too hard for you to replace the scanning part with older code.

**Comment by zentechthaingo** [comment]
Thanks, mashbrige.
