### ISSUE TITLE
all beacon scanned are locked

### ISSUE THREAD

**Issue by DarkAulius** [google/beacon-platform#2]
i've change multiple namespaceId and instanceId but when scan with demo app i retrieve everytime locked simbol near eddystone beacon. Any solution?

**Comment by marcwan** [comment]
Hi @DarkAulius !

Two questions:  Are you talking about the iOS or Android version of the service demo app?  Also, what beacons are you using — are they yours and registered already, or new beacons?

A locked icon (in both iOS and Android) means that the beacon was registered by somebody else, and your account doesn't have access to it via the Proximity Beacon Admin APIs …

**Comment by DarkAulius** [comment]
1) android
2) new kontakt beacons

**Comment by marcwan** [comment]
Hi @DarkAulius!

The Android guy is out for a few days, but from looking at the code, it looks as though one of two things will cause the lock icon to appear:

1. If the beacon is registered to somebody other than you (doesn't sound like it's the case here).
2. It's possible that this error could also be triggered if you're not property authenticated against the APIs. Are you sure your API Console project requested access to the Proximity Beacon API (and not the Proximity Pairing API)?

**Comment by tamsler** [comment]
I am having the same issue. I registered a ClientID and have enabled the Google Proximity Beacon API

**Comment by tamsler** [comment]
I got it working, but I had to change the source code. I change:

from:
namespace.setText(sharedPreferences.getString("namespace", "01020304050607080910"));

to:
namespace.setText(sharedPreferences.getString("namespace", "01020304050607080911"));

Note once you edit the beacon for the first time, you will see a bunch of "page not found 404" error dialogs. Just ignore them.

**Comment by Diolor** [comment]
Hope this helps: 

I have Radius Network USB beacons. The beacons have their id reset every time they lose power so they are registered to someone else.

Be sure that you have enabled the API in the Console & the id is unique (e.g. generated by url: yourownwebsite.com).

**Comment by mashbridge** [comment]
Glad to hear everything's working now. We've updated the README to be very clear that you *must* set up the client id authorisation in the developers console. 100% of "all my scanned beacons are locked" issues are a result of missing a step here, having the wrong package name/SHA1 hash, or similar.

@Diolor If by ID you mean the BD_ADDR device address, that's fine. But if you mean that the Eddystone UID is changing, that sounds like a bug with their firmware. Feel free to open an issue on github.com/google/eddystone and we'll investigate with them. Thanks!
