### ISSUE TITLE
Installation failed with message INSTALL_FAILED_OLDER_SDK.

### ISSUE THREAD

**Issue by harry2011** [google/beacon-platform#27]
I am using Android Studio version 1.3.2 and getting error "Installation failed with message INSTALL_FAILED_OLDER_SDK." on Run -> Run App after importing as existing project, and if m not wrong importing BeaconServiceDemoApp folder as an existing project is by clicking the option Import project as (Gradle, Eclipse ADT etc)

**Comment by harry2011** [comment]
![installation error](https://cloud.githubusercontent.com/assets/17031608/12760120/d723af08-ca0a-11e5-9d96-b065f7b1756d.jpg)

**Comment by mashbridge** [comment]
Sounds like the device you're trying to install onto is something less than API 22, which is in the build.gradle here: https://github.com/google/beacon-platform/blob/master/samples/android/BeaconServiceDemoApp/app/build.gradle

If you're on Lollipop try changing the minSdkVersion and targetSdkVersion versions to 21 -- the app should still work back to 21.
