### ISSUE TITLE
ld: library not found for -lPods in iOS

### ISSUE THREAD

**Issue by manoomanish** [google/beacon-platform#29]
![screen shot 2016-05-23 at 12 32 00 pm](https://cloud.githubusercontent.com/assets/16221767/15462753/6dc45466-20e2-11e6-986f-7fe386cb5752.png)

I got this issue. I tried hard to overcome but did not found any related help to solve this.

**Comment by renekiel** [comment]
I have the same error. I'm using XCode 7.3.1 and CocoaPods 1.0.1. Any help is appreciated.

**Comment by po5i** [comment]
+1

**Comment by po5i** [comment]
This answer did the solution for me: http://stackoverflow.com/a/26734273

**Comment by marcwan** [comment]
Looks like that's it. Thanks for the link!
