### ISSUE TITLE
Click SCAN button but no beacon being discovered

### ISSUE THREAD

**Issue by hangg7** [google/beacon-platform#33]
Hi,
I just tried out this demo app, but I just cannot discover any beacons around my phone.

I have registered the API key and OAuth 2.0 client ID successfully and turned on Proximity API on the console. And I can actually access to the beacons using my hand-made app, so it should be something wrong with the way I use this demo.

Any advice would be appreciated.

**Comment by marcwan** [comment]
Is this the android or iOS app?
