### ISSUE TITLE
Registering Nearby Notifications using Proximity Beacon API

### ISSUE THREAD

**Issue by divye01** [google/beacon-platform#38]
I would like to know if it is possible to register/confogure Nearby Notifications of a particular beacon using the Proximity Beacon API.

**Comment by afitz0** [comment]
HI @divye01 ,

Yes, absolutely! Check out the python samples (aka `pb-cli`), and specifically the example on [Creating Attachments](https://github.com/google/beacon-platform/tree/master/samples/python#create-an-attachment). To amend that example to Nearby Notifications, you might run a command that looks like:

```
pb-cli <creds> create-attachment \
    --beacon-name $beacon_name \
    --namespaced-type com.google.nearby/en \
    --data '{"title": "Example Notification", "url": "https://www.example.com/"}'
```

In other words, as long as your attachment follows the rules outlined in the [Attachment Data Format documentation](https://developers.google.com/nearby/notifications/attachment_data_format), you should be able to register/configure Nearby Notifications via the API. As always, after running these you may want to double check your work via the [dashboard](https://developers.google.com/beacons/dashboard/).

**Comment by divye01** [comment]
Thanks @afitz0!

**Comment by thehypnoguy** [comment]
Do you have any references on setting this up using the PHP Google Client as set up on GitHub

Thanks
Martin Blakley
